# Generated by Django 5.0.3 on 2024-03-28 21:43

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    This is a Migration Class written extending/overwriting the Migration class of Django.

    This class is dependent on the operations of "0001_initial.py"

    This class does the following operations on the user model:\n
    - is_manager field is removed\n
    - user_type field is added with Customer, Cashier, and Manager choices\n
    - name field is altered with a maximum character length of 100\n
    """


    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_manager',
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.IntegerField(choices=[(0, 'Customer'), (1, 'Cashier'), (2, 'Manager')], null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
