# Generated by Django 5.0.3 on 2024-03-28 21:54

from django.db import migrations


class Migration(migrations.Migration):
    """
    This is a Migration Class written extending/overwriting the Migration class of Django.

    This class is dependent on the operations of "0002_remove_user_is_manager_user_user_type_and_more.py"

    This class removes the clocked_time field from the user model.
    """

    dependencies = [
        ('app', '0002_remove_user_is_manager_user_user_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='clocked_time',
        ),
    ]
