# Generated by Django 5.0.3 on 2024-03-28 22:48

from django.db import migrations


class Migration(migrations.Migration):
    """
    This is a Migration Class written extending/overwriting the Migration class of Django.

    This class is dependent on the operations of "0003_remove_user_clocked_time.py"

    This class does the following operations on the menuinventory model:\n
    - "inventory" is renamed to "inventory_id"\n
    - "menu" is renamed to "menu_id"\n
    """

    dependencies = [
        ('app', '0003_remove_user_clocked_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuinventory',
            old_name='inventory',
            new_name='inventory_id',
        ),
        migrations.RenameField(
            model_name='menuinventory',
            old_name='menu',
            new_name='menu_id',
        ),
    ]
