# Generated by Django 5.0.3 on 2024-03-28 22:49

from django.db import migrations


class Migration(migrations.Migration):
    """
    This is a Migration Class written extending/overwriting the Migration class of Django.

    This class is dependent on the operations of "0004_rename_inventory_menuinventory_inventory_id_and_more.py"

    This class does the following operations on the menuinventory model:\n
    - "inventory_id" is renamed to "inventory"\n
    - "menu_id" is renamed to "menu"\n
    """

    dependencies = [
        ('app', '0004_rename_inventory_menuinventory_inventory_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuinventory',
            old_name='inventory_id',
            new_name='inventory',
        ),
        migrations.RenameField(
            model_name='menuinventory',
            old_name='menu_id',
            new_name='menu',
        ),
    ]
