# Generated by Django 5.0.3 on 2024-04-12 20:34

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    This is a Migration Class written extending/overwriting the Migration class of Django.

    This class is dependent on the operations of "0005_rename_inventory_id_menuinventory_inventory_and_more.py"

    This class does the following operations:\n
    - name field in inventory is now a Text Field\n
    - description field in menu is now a Text Field\n
    - season_end field in menu is now a Character Field\n
    - season_start field in menu is now a Character Field\n
    - is_completed field in order is a Boolean Field\n
    - timestamp field in order is a Character Field\n
    - email field in user is a Unique Text Field\n
    - name field in user is a Character Field\n
    - user_type field in user is altered to have Customer, Cashier, and Manager choices\n
    """

    dependencies = [
        ('app', '0005_rename_inventory_id_menuinventory_inventory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='menu',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='menu',
            name='season_end',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='menu',
            name='season_start',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_completed',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='timestamp',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.IntegerField(choices=[(0, 'Customer'), (1, 'Cashier'), (2, 'Manager')], default=1),
        ),
    ]
