# Generated by Django 5.0.3 on 2024-04-23 14:22

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    This is a Migration Class written extending/overwriting the Migration class of Django.

    This class is dependent on the operations of "0008_menu_display_alter_order_employee.py"

    This class does the following operations:\n
    - category field in menu is a Integer Field with Burgers, Baskets, Sandwiches, Shakes n Sweets, Beverages, Sides and Sauces\n
    - description field in menu is now a Text Field\n
    """

    dependencies = [
        ('app', '0008_menu_display_alter_order_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='category',
            field=models.IntegerField(choices=[(0, 'Burgers'), (1, 'Baskets'), (2, 'Sandwiches'), (3, 'Shakes n Sweets'), (4, 'Beverages'), (5, 'Sides'), (6, 'Sauces')]),
        ),
        migrations.AlterField(
            model_name='menu',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
